INSERT OR IGNORE INTO reference_values (category, value) VALUES
('lps_class', 'I'),
('lps_class', 'II'),
('lps_class', 'III'),
('lps_class', 'IV'),
('qa_severity', 'info'),
('qa_severity', 'warning'),
('qa_severity', 'error'),
('qa_severity', 'critical'),
('qa_status', 'pending'),
('qa_status', 'ok'),
('qa_status', 'warning'),
('qa_status', 'error'),
('qa_status', 'skipped'),
('cad_layer_type', 'roof'),
('cad_layer_type', 'fve'),
('cad_layer_type', 'lps'),
('cad_layer_type', 'dc_route'),
('cad_layer_type', 'ac_route'),
('cad_layer_type', 'notes'),
('cad_layer_type', 'map'),
('document_type', 'report'),
('document_type', 'protocol'),
('document_type', 'datasheet'),
('document_type', 'drawing'),
('document_type', 'export_package'),
('export_type', 'json'),
('export_type', 'pdf'),
('export_type', 'docx'),
('export_type', 'zip'),
('export_type', 'cad_preview'),
('spd_type', 'DC T1+T2'),
('spd_type', 'DC T2'),
('spd_type', 'AC T1+T2'),
('spd_type', 'AC T2'),
('fve_component', 'panel'),
('fve_component', 'string'),
('fve_component', 'inverter'),
('fve_component', 'optimizer'),
('fve_component', 'dc_route'),
('fve_component', 'ac_route'),
('lps_component', 'air_terminal'),
('lps_component', 'mesh'),
('lps_component', 'downconductor'),
('lps_component', 'hvi'),
('lps_component', 'earthing'),
('lps_component', 'lpz');
